#!/bin/zsh
#  _                                                    _            __ _               
# | |                                                  | |          / _| |              
# | |__   ___  _ __ ___   ___ ________      _____  _ __| | ________| |_| | _____      __
# | '_ \ / _ \| '_ ` _ \ / _ \______\ \ /\ / / _ \| '__| |/ /______|  _| |/ _ \ \ /\ / /
# | | | | (_) | | | | | |  __/       \ V  V / (_) | |  |   <       | | | | (_) \ V  V / 
# |_| |_|\___/|_| |_| |_|\___|        \_/\_/ \___/|_|  |_|\_\      |_| |_|\___/ \_/\_/  
                                                                                       
                                                                                       

cd desktop
mkdir -p homework
mkdir -p homework/{file,img,data,ref}
cd homework

touch student_id.docx file/a.md

cp ~/downloads/*.jpg img/
cp ~/downloads/*.jpeg img/
cp ~/downloads/*.png img/
cp ~/downloads/*.xlsx data/
cp ~/downloads/*.csv data/
cp ~/downloads/*.html data/


open file/a.md student_id.docx
