#!/bin/zsh
cd desktop
mkdir -p homework
mkdir -p homework/{file,img,data,ref}
cd homework

touch student_id.docx file/a.md

cp ~/downloads/*.jpg img/
cp ~/downloads/*.jpeg img/
cp ~/downloads/*.png img/
cp ~/downloads/*.xlsx data/
cp ~/downloads/*.csv data/
cp ~/downloads/*.html data/


open file/a.md student_id.docx
